name: Acorn Setup
description: 'Installs Acorn'
author: 'Acorn Labs, Inc.'
branding:
  icon: terminal
  color: purple
inputs:
  acorn-version:
    description: 'Version of acorn to install'
    default: latest
    required: false
  acorn-init:
    description: Whether to initialize acorn in the cluster
    required: false
    default: 'true'

  k3s-install:
    description: Whether to install k3s or not
    required: false
    default: 'true'
  k3s-version:
    description: 'Version of k3s to install'
    default: latest
    required: false
  k3s-cleanup:
    description: Cleanup k3s container after running'
    required: false
    default: 'true'

runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
